USE planer;

INSERT INTO city(name, description)
VALUES ("Gdańsk",
        "Miasto w województwie pomorskim, położone nad Morzem Bałtyckim u ujścia Motławy do Wisły nad Zatoką Gdańską.\nCentrum kulturalne, naukowe i gospodarcze oraz stolica województwa pomorskiego."),
       ("Gdynia",
        "Miasto w województwie pomorskim, położone nad Morzem Bałtyckim. Wchodzi w skład Trójmiasta (wraz z Gdańskiem i Sopotem).\nJest najludniejszym w Polsce miastem niewojewódzkim z wieloma ciekawymi restauracjami i dostępem do plaży."),
       ("Warszawa",
        "Stolica Polski i województwa mazowieckiego, największe miasto w kraju, położone w jego centralnej części,\nna Nizinie Środkowomazowieckiej, na Mazowszu, nad Wisłą."),
       ("Kraków",
        "Miasto położone w południowej Polsce nad Wisłą, drugie co do liczby mieszkańców i powierzchni miasto kraju.\nFormalna stolica Polski do 1795 roku i miasto koronacyjne oraz nekropolia królów Polski. Kraków jest stolicą historycznej Małopolski.\nLeży na obszarze Bramy Krakowskiej, Niecki Nidziańskiej i Pogórza Zachodniobeskidzkiego."),
       ("Wrocław",
        "Miasto w południowo-zachodniej Polsce. Położone na Nizinie Śląskiej, nad Odrą i czterema jej dopływami.\nJest historyczną stolicą Dolnego Śląska, a także całego Śląska. Jest głównym miastem aglomeracji wrocławskiej.\nTrzecie pod względem liczby ludności miasto w Polsce"),
       ("Sopot",
        "Sopot (kaszub. Sopòt lub też Sopòtë, Copòtë, Copòt, niem. Zoppot)– miasto na prawach powiatu w północnej Polsce nad Zatoką Gdańską (Morze Bałtyckie), położone na Pobrzeżu Gdańskim, między Gdańskiem a Gdynią, z którymi tworzy Trójmiasto, w obrębie aglomeracji trójmiejskiej. Jest najmniejszym pod względem liczby ludności miastem na prawach powiatu w Polsce oraz najmniejszym pod tym samym względem miastem, którego organem władzy wykonawczej jest prezydent (a nie burmistrz)."),
       ("Poznań",
        "Poznań, Stołeczne Miasto Poznań – miasto na prawach powiatu w zachodniej Polsce, położone na Pojezierzu Wielkopolskim, nad rzeką Wartą, u ujścia Cybiny. Historyczna stolica Wielkopolski, od 1999 r. siedziba władz województwa wielkopolskiego i powiatu poznańskiego. Piąte pod względem liczby ludności miasto w Polsce i ósme pod względem powierzchni (261,9 km²). Poznań wraz z powiatem poznańskim i gminami Oborniki, Skoki, Szamotuły i Śrem tworzy aglomerację poznańską, zamieszkałą przez ponad 1,2 mln osób. W 2018 think tank Globalization and World Cities (GaWC), badający wzajemne stosunki pomiędzy miastami świata w kontekście globalizacji, uznał Poznań za metropolię globalną (Gamma-). Poznań często plasuje się w czołówce miast o bardzo wysokiej jakości edukacji i bardzo wysokim standardzie życia. Zajmuje również wysokie miejsce pod względem bezpieczeństwa i jakości opieki zdrowotnej. Miasto Poznań wielokrotnie zdobyło także nagrodę „Superbrands” za markę miasta bardzo wysokiej jakości.");

INSERT INTO place (description, name, price, rate, type, city_id)
VALUES ("Bazylika konkatedralna Wniebowzięcia Najświętszej Maryi Panny, zwana często „Koroną Gdańska” jest największą w Europie świątynią wybudowaną z cegły.Jej potężne mury i wieże wznoszą się wysoko nad panoramą miasta oraz nad rozległą okolicą.",
        "Bazylika Mariacka",
        12,
        4,
        "MONUMENT",
        1),
       ("Wzgórze Pachołek z 15 metrową wieżą widokową znajdujące się w Oliwie. Można podziwiać wspaniałą panoramę Gdańska oraz pospacerować lasem.",
        "Wzgórze Pachołek-Wieża Widokowa",
        0,
        5,
        "NATURE",
        1),
       ("Zabytkowy park w dzielnicy Oliwa, nad Potokiem Oliwskim. Powierzchnia parku wynosi 11,3 ha.",
        "Park Oliwski",
        0,
        4.5,
        "NATURE",
        1),
       ("Zabytkowa fontanna. Stoi w najbardziej reprezentacyjnej części Gdańska – na Długim Targu, przed wejściem do Dworu Artusa.",
        "Fontanna Neptuna",
        0,
        4,
        "MONUMENT",
        1),
       ("Mieszanka rutyny, młodości, pasji, perfekcjonizmu, elementy polskiej tradycji, powiew kuchni świata, super pierogi. Kilka lokalizacji w Gdańsku",
        "Pierogarnia Mandu",
        0,
        4.7,
        "RESTAURANT",
        1),
       ("Dwa wieżowce o charakterze mieszkalnym i biurowo-usługowym zlokalizowane w śródmieściu Gdyni, zbudowane w latach 2006-2009. Całkowita wysokość wyższej wieży to 141,6 m, a niższej 91 m.W rankingu wysokości wieżowców Polsce wyższa wieża znajduje się na 12. miejscu. Można wjechać na punkt widokowy.",
        "Sea Towers",
        20,
        4,
        "MONUMENT",
        2),
       ("Drewniane molo znajdujące się w nadmorskiej, południowo-wschodniej dzielnicy Gdyni. Należy do najchętniej odwiedzanych obiektów w mieście.",
        "Molo Orłowo",
        0,
        5,
        "NATURE",
        2),
       ("Długi, szybko ulegający erozji klif poprzecinany leśnymi ścieżkami. Rozciąga się z niego widok na Zatokę Gdańską.",
        "Klif Orłowski",
        0,
        4.6,
        "NATURE",
        2),
       ("Trzymasztowy żaglowiec szkolny zakupiony przez społeczeństwo Pomorza w 1929 dla Szkoły Morskiej w Gdyni. Od 1982 zacumowany w Gdyni jako statek-muzeum, oddział Narodowego Muzeum Morskiego w Gdańsku.",
        "Statek-Muzeum Dar Pomorza",
        26,
        4.2,
        "MONUMENT",
        2),
       ("NEON to kuchnia z azjatyckim twistem. Wszystkie potrawy są przygotowywane na miejscu. W kuchni rządzi Jan Kilański - laureat polskiego Top Chefa.",
        "Neon",
        0,
        4.6,
        "RESTAURANT",
        2),
       ("Pałac Kultury i Nauki drugi pod względem wysokości całkowitej budynek w Polsce. Znajduje się w śródmieściu Warszawy, przy placu Defilad 1.W 2007 budynek został wpisany do rejestru zabytków. Pałac stanowił dar narodu radzieckiego dla narodu polskiego. Możliwośc wjechania na taras widokowy oraz zwiedzenia muzeum.",
        "Pałac Kultury i Nauki",
        20,
        4.6,
        "MONUMENT",
        3),
       ("Barokowo-klasycystyczny zamek królewski znajdujący się w Warszawie przy placu Zamkowym 4. Pełni funkcje muzealne i reprezentacyjne. Pierwotnie rezydencja książąt mazowieckich, a od XVI wieku siedziba władz I Rzeczypospolitej: króla i Sejmu.",
        "Zamek Królewski w Warszawie",
        15,
        3.9,
        "MONUMENT",
        3),
       ("Park miejski w śródmieściu Warszawy, położony między placem marsz. Józefa Piłsudskiego, placem Żelaznej Bramy, ul. Marszałkowską i ul. Królewską, na Osi Saskiej.Pierwotnie geometryczny ogród francuski założony w latach 1724-1748 dla króla Augusta II Mocnego jako ogród pałacu Saskiego.",
        "Ogród Saski w Warszawie",
        0,
        4.3,
        "NATURE",
        3),
       ("Zespół pałacowo-ogrodowy w Warszawie założony w XVIII wieku przez Stanisława Augusta Poniatowskiego. Nazwa pochodzi od barokowego pawilonu Łaźni, wzniesionego w latach 80.XVII wieku przez Stanisława Herakliusza Lubomirskiego i przebudowanego przez Stanisława Augusta Poniatowskiego na pałac Na Wyspie.",
        "Łazienki Królewskie",
        0,
        4.2,
        "NATURE",
        3),
       ("Monument znajdujący się przy ul. Wybrzeże Kościuszkowskie. Rzeźba przedstawia postać Syreny z uniesionym mieczem i tarczą. Wzrok ma skierowany na północ, a jej mocny kobiecy korpus osłania trzymana w lewej ręce okrągła, lekko wypukła tarcza. Na tarczy znajduje się wizerunek orła w koronie, wokół którego biegnie napis Warszawa",
        "Pomnik Syreny nad Wisłą",
        0,
        4.7,
        "MONUMENT",
        3),
       ("Bezpretensjonalna restauracja serwująca koktajle oraz pizzę w stylu neapolitańskim z różnymi dodatkami.",
        "Pizzaiolo",
        0,
        4.4,
        "RESTAURANT",
        3),
       ("Zamek obronno-rezydencyjny w Krakowie, na wzgórzu Wawelskim.Mają w nim siedzibę Państwowe Zbiory Sztuki - Zamek Królewski na Wawelu, muzeum o powierzchni 7040 m² z 71 salami wystawowymi.",
        "Zamek Królewski na Wawelu",
        40,
        4.3,
        "MONUMENT",
        4),
       ("Sukiennice - zabytkowy budynek sukiennic znajdujący się w Krakowie na Starym Mieście, pośrodku Rynku Głównego. ",
        "Sukiennice",
        0,
        5.0,
        "MONUMENT",
        4),
       ("Planty - park miejski w Krakowie otaczający Stare Miasto. Został założony w latach 1822-1830, ma powierzchnię 21 ha i ok. 4 km długości.",
        "Planty",
        0,
        4.9,
        "NATURE",
        4),
       ("Kopiec Kościuszki - jeden z pięciu kopców krakowskich, poświęcony Tadeuszowi Kościuszce, znajduje się na Górze św. Bronisławy w zachodniej części Krakowa na terenie Dzielnicy VII Zwierzyniec.",
        "Kopiec Kościuszki",
        0,
        4.2,
        "NATURE",
        4),
       ("Kameralna, przytulna restauracja z 2 salami i barem serwująca pożywne nowoczesne dania i szeroki wybór wódek.",
        "Restauracja Starka Kraków",
        0,
        4.0,
        "RESTAURANT",
        4),
       ("Muzeum sztuki we Wrocławiu, założone w 1893 we Lwowie, od 1980 we Wrocławiu eksponuje cykloramiczny obraz Bitwa pod Racławicami namalowany w latach 1893-1894 przez zespół malarzy pod kierunkiem Jana Styki i Wojciecha Kossaka. ",
        "Muzeum Panorama Racławicka",
        25,
        4.8,
        "MONUMENT",
        5),
       ("Znajduje się w Parku Szczytnickim w Śródmieściu Wrocławia. W ogrodzie zgromadzono prawie 270 taksonów 		roślin drzewiastych. ",
        "Ogród Japonski",
        0,
        4.7,
        "NATURE",
        5),
       ("Średniowieczny plac targowy we Wrocławiu, obecnie centralna część strefy pieszej. Jeden z największych rynków staromiejskich Europy, z największymi ratuszami w Polsce. Rynek wrocławski, według Olgierda Czernera, obejmuje cały teren placu wraz z wszystkimi elementami architektonicznymi znajdującym się na jego obszarze oraz zabudowę otaczającą plac z czterech stron.",
        "Wrocławski Rynek",
        0,
        4.5,
        "NATURE",
        5),
       ("Dwuprzęsłowy stalowy, nitowany most we Wrocławiu zbudowany w roku 1889 nad północną odnogą Odry pomiędzy Ostrowem Tumskim a Wyspą Piasek, na miejscu wcześniejszego mostu drewnianego",
        "Most Tumski",
        0,
        3.9,
        "NATURE",
        5),
       ("Tradycyjne czeskie potrawy, kawa i piwo w rustykalnym lokalu z tarasem.",
        "Pepik PUB",
        0,
        4.7,
        "RESTAURANT",
        5),
       ("Molo w Sopocie im. Jana Pawła II – najdłuższe molo nad Morzem Bałtyckim. Ma około pół kilometra długości – część spacerowa ma 511,5 m, z czego 458 m wchodzi w głąb Zatoki Gdańskiej. Jest jedną z największych atrakcji miasta. W głowicy mola jest zlokalizowana przystań morska „Molo” w Sopocie.",
        "Molo w Sopocie",
        12,
        4.2,
        "NATURE",
        6),
       ("Nazwa jeziora pochodzi od kawalerów maltańskich, czyli rycerzy z zakonu joannitów, którzy mieli tu swoją siedzibę, kościół i hospicjum. Jezioro, na którym odbywa się wiele ważnych regat kajakarskich i wioślarskich, powstało w 1952 r. poprzez spiętrzenie wód rzeki Cybiny i ma powierzchnię 64 ha. Tor regatowy (jeden z najlepszych w Europie) ma 2190 m długości i 170-400 m szerokości. W zachodniej części jeziora znajduje się największa w Poznaniu fontanna, ufundowana dla upamiętnienia 750. rocznicy założenia miasta. Wzdłuż północnego brzegu jeziora przebiega trasa wąskotorowej Kolejki Parkowej Maltanka, której końcowa stacja - Zwierzyniec - usytuowana jest w pobliżu wejścia do Wielkopolskiego Parku Zoologicznego (Nowe Zoo). Na południowym brzegu - na kopcu Wolności - znajduje się sztuczny, całoroczny stok narciarski oraz letni tor saneczkowy. U stóp kopca czynne jest pole do nauki gry w golfa oraz tor do minigolfa. W pobliżu jest także kąpielisko.",
        "Jeziora Maltańske w Poznaniu",
        0,
        4.6,
        "NATURE",
        7),
       ("Stary Rynek (początkowo Rynek, od XIX wieku Alter Markt, obecna nazwa od 16 czerwca 1919 – główny plac miejski w Poznaniu wytyczony ok. 1253 roku jako centralne miejsce miasta lokacyjnego. Jest kwadratem o boku długości 141 metrów, a z każdej ze ścian wychodzą trzy ulice, z czego dwie skrajne z narożników. Znajduje się na Starym Mieście, w ramach osiedla administracyjnego Stare Miasto. Jest trzecim co do wielkości rynkiem w Polsce (po krakowskim i wrocławskim) i jednym z większych w Europie.",
        "Stary Rynek Poznań",
        0,
        47,
        "MONUMENT",
        7);



INSERT INTO image (url, place_id, city_id)

VALUES ("https://s-trojmiasto.pl/zdj/c/n/9/2825/999x0/2825085-Bazylika-Mariacka-to-najwiekszy-w-Europie-kosciol-wzniesiony-z-cegly-Jej-budowa-trwala-ok-150-lat-a-dokladnie-odbyla-sie-w-latach-1346-1502.jpg",
        1, 1),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/48343.jpg", 2, 1),
       ("https://download.cloudgdansk.pl/gzdiz-pl/t/2023054663.jpg", 2, 1),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/48853.jpg", 2, 1),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/48879.jpg", 2, 1),
       ("https://download.cloudgdansk.pl/gdansk-pl/t/202208193602.jpg", 2, 1),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/23137.jpg", 2, 1),
       ("https://v.wpimg.pl/NTI4MzA5YTUoVjtJbk5sIGsObxMoF2J2PBZ3WG56YWJ9BDVOcwJhPWdDPVQxWWE1ZlJiEDFQKXt6BXtKcho-NTtfEhUtXDknIl0SKiBBPC0iawYVMlgnMCxGYxAxUCl2NA",
        3, 1),
       ("https://wenecjusz.pl/wp-content/uploads/2019/12/gdansk-20-1.jpg", 4, 1),
       ("https://pojedztam.pl/wp-content/uploads/2019/04/Pierogarnia-Mandu-w-Gdansku.jpg", 5, 1),
       ("https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/00_sea_towers_%28April_2018%29.jpg/1280px-00_sea_towers_%28April_2018%29.jpg",
        6, 2),
       ("https://yacht-club-sea-towers-premium-gdynia.booked.com.pl/data/Photos/OriginalPhoto/11918/1191817/1191817516/Yacht-Club-Sea-Towers-Premium-Apartment-Gdynia-Exterior.JPEG",
        6, 2),
       ("https://i.wpimg.pl/960x720/i1.nocimg.pl/d13/1721/153-gdynia-sylwester-2014-2015.png", 6, 2),
       ("https://seatowersgdynia.pl/wp-content/uploads/2019/06/seatowers-550x660.jpg",
        6, 2),
       ("https://www.worldisbeautiful.eu/up_files/1175-Molo-w-Orlowie.jpg", 7, 2),
       ("https://www.gdynia.pl/cache/images/1400x0/b64b1f75ee97d390c14d0eae3a1b5b41.jpg", 8, 2),
       ("https://nmm.pl/wp-content/uploads/2021/10/01_Dar-Pomorza.jpg", 9, 2),
       ("https://lh3.googleusercontent.com/p/AF1QipMNNW7wQfAf93F3rFxIRrOUp6RFChN0_-f2L8SU=w1080-h608-p-no-v0", 10, 2),
       ("https://pkin.pl/wp-content/uploads/articles/phpu0wsSU_5ae85fdb14f5a.jpg", 11, 3),
       ("https://www.zamek-krolewski.pl/sites/default/files/2022/03/1342/fotorelacja/120921%20ZAMEK%20DRON%2030.jpg",
        12, 3),
       ("https://ddob.com/uploads/pjanicki/4f6a014cc8c0e12ab869a571395fbc14.jpg",
        13, 3),
       ("https://modanamazowsze.pl/wp-content/uploads/2021/03/glowne-1-1170x680.jpg",
        13, 3),
       ("https://warsawtour.pl/wp-content/uploads/2018/08/%C5%81azienki-Kr%C3%B3lewskie-Pa%C5%82ac-na-Wyspie_fot.-m.st_.-Warszawa.jpg",
        14, 3),
       ("https://4.bp.blogspot.com/-8SzFMKoYagw/WLx23r7ZRdI/AAAAAAAAQ54/2OXTr9wT1AslI5SBPWFC907AdC4_OyozwCLcB/s1600/syrena%2B4.jpg",
        15, 3),
       ("https://4.bp.blogspot.com/-ssHOb3qMUy0/WLx23TPpNyI/AAAAAAAAQ50/ZBcRAgH9x_0qS9tEzrfOCo-GIz6PejDVgCLcB/s1600/syrena%2B1.jpg",
        15, 3),
       ("https://pyzamadeinpoland.pl/wp-content/uploads/2020/11/pizzaiolo-dwa-osiem-11.jpg", 16, 3),
       ("https://assets.ey.com/content/dam/ey-sites/ey-com/pl_pl/home-index/ey-cracow-shutterstock_1783414247.jpg", 17,
        4),
       ("https://www.ing.pl/_fileserver/item/1125389.fedcba", 17, 4),
       ("https://czasdzieci.pl/pliki/wycieczki/w_p_683_7ae5a.jpg", 17, 4),
       ("https://ocdn.eu/images/pulscms/OGI7MDA_/385cba4c-1b9e-4015-88e3-dec6ae892f20.jpeg", 17, 4),
       ("http://media.krakow.travel/photos/49539/xxl.jpg", 18, 4),
       ("https://meteor-turystyka.pl/images/places/0/28.jpg", 18, 4),
       ("https://www.national-geographic.pl/media/cache/big/uploads/media/default/0014/39/krakow.jpeg", 18, 4),
       ("https://www.morizon.pl/blog/wp-content/uploads/2015/06/krakow-4439817_640.jpg", 18, 4),
       ("https://krakowmonamour.com/wp-content/uploads/2020/12/Planty-Park-Krakow.jpg", 19, 4),
       ("https://orlegniazda.pl/Media/Default/.MainStorage/ContentItemDocumentTypeRecord/0mpzsjha.fn1/planty.JPG", 19,
        4),
       ("https://krakow.wiki/wp-content/uploads/2016/10/planty.jpg", 19, 4),
       ("https://cdn.getyourguide.com/img/tour/a2568e7d9fc18e02.jpeg/145.jpg", 20, 4),
       ("https://jura.slaskie.travel/Media/Default/.MainStorage/ContentItemDocumentTypeRecord/oyd0r1it.bso/starka1.jpg",
        21, 4),
       ("https://all.accor.com/magazine/imagerie/wroclaw-f786.jpg", 24, 5),
       ("https://www.niesamowitapolska.eu/images/dolnoslaskie/wroclaw-i-okolice/artykuly/panorama-raclawicka/FD8A6441.JPG",
        22, 5),
       ("https://s3.eu-central-1.amazonaws.com/pressland-cms/cache/article_show_cover/3a/6175486-ogrod-japonski-to-brama-wejsciowa-do-uchi-roji-dalej.jpeg",
        23, 5),
       ("https://i.wpimg.pl/O/644x429/d.wpimg.pl/1682314221--1017701063/wroclaw-rynek-miejski.jpg", 24, 5),
       ("https://explorista.nl/wp-content/uploads/2019/04/Wroclaw2.jpg", 24, 5),
       ("https://www.geogr.uni.wroc.pl/ts1/r=w:2000%7Ch:1500&img=tourism_and_hospitality_blog/14/lib-01.jpg", 24, 5),
       ("https://mapy.emiejsca.pl/zdjecia/wroclaw-klodki-most-tumski-32.jpg", 25, 5),
       ("http://pepik.pl/wp-content/uploads/2012/09/pub-5.jpg", 26, 5),
       ("https://www.worldisbeautiful.eu/up_files/1910-Sopockie-molo-noca.jpg", 27, 6),
       ("https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Muelle_de_Sopot%2C_Polonia%2C_2013-05-22%2C_DD_21.jpg/800px-Muelle_de_Sopot%2C_Polonia%2C_2013-05-22%2C_DD_21.jpg",
        27, 6),
       ("https://pomorskie.travel/wp-content/uploads/2020/04/SOPOT-MOLO-1110x670.jpg", 27, 6),
       ("https://u.profitroom.pl/2020-andersiahotel-pl/thumb/2560x1440/uploads/Zdjecia_stokowe/Andersia_o_hotelu_stary_rynek01.jpg",
        29, 7),
       ("https://bi.im-g.pl/im/73/5a/19/z26583923IEG,Jezioro-Maltanskie-z-lotu-ptaka.jpg", 28, 7),
       ("https://radiopoznan.fm/uploads/assets/fcwtee5f0u89f8s_jezioro-malta-plywanie.jpg", 28, 7);

INSERT INTO opinions (rate, comment, place_id, user_id)
VALUES (5,
        "Bazylika monumentalna, wielkość robi ogromne wrażenie a wewnątrz nieomal muzeum - mnóstwo fantastycznych zabytków. Rzeźb, obrazów, malowideł. Przepiękna rzeźba Madonny, zegar astronomiczny, kopia ołtarza Memlinga (oryginał w Muzeum Narodowym w Gdańsku) przepiękne ołtarze w bocznych kaplicach. Gdyby się chciało zobaczyć każde dzieło sztuki trzeba by w bazylice spędzić cały dzień. Jest to także miejsce kultu, więc w trakcie zwiedzania należy zachować powagę i przestrzegać godzin nabożeństw podczas których zwiedzać nie należy.",
        1, 1),
       (5,
        "Najważniejszy punkt podczas zwiedzania Gdańska poza Żurawiem i pomnikiem Neptuna. Bazylika która jest kawałem historii dla Gdańska oraz całego kraju. W środku tak na prawdę poza kościołem to olbrzymie muzeum z olbrzymią ilością eksponatów, pomników z wielu różnych okresów. Świetnie zachowana. Robi niesamowite wrażenie swoją potęgą. Być na starym mieście i nie odwiedzić to tak jakby w pewnym sensie nie być 🙂 Polecam wszystkim zwiedzającym i zachęcam do dokładnego zwiedzania 🙂",
        1,2),
       (4,
        "Bazylika różniącą się od innych. Ogromna przestrzeń w środku ale niemal pusta. Brak sztukaterii czy złota i innego przepychu co jest ogromną rzadkością jak na kościół.. Bardzo dużo historycznych przedmiotów i rzeźb. Niemal jak muzeum. To moje trzecie odwiedziny Gdańska więc tym razem nie wchodziłem na górę jednak każdego zachęcam do zobaczenia Gdańska z góry. Piękne widoki.",
        1, 1),
       (4,
        "Bardzo ładny widok na Gdańsk i okolice,warto pokonać kilka dziesiąt schodów ,potem powspinac się na wieżę widokowa  aby te widoki podziwiać",
        1, 1),
       (5,
        "W gdańskiej dzielnicy Oliwa, na wzgórzu o nazwie Pachołek stoi współczesna 15-metrowa wieża widokowa. Jest ona oddalona o około 1,5 km od ZOO. Warto wybrać się tutaj na spacer. Jeżeli chcielibyście się dostać na ten punkt widokowy to możecie wejść po około 400 schodach z ulicy Spacerowej lub wybrać mniej stromą drogę idąc przez las od ulicy Tatrzańskiej. Trochę poniżej platformy widokowej jest kolejny punkt widokowy (Widok VIII \u2013 Tomasz). To opcja dla osób, które nie mogą wejść na wieżę widokową. Wejście na wieżę jest bezpłatne."
           , 2, 1),
       (4,
        "Bardzo ładny widok na Gdańsk i okolice,warto pokonać kilka dziesiąt schodów ,potem powspinac się na wieżę widokowa  aby te widoki podziwiać"
           , 2, 1),
       (4
           ,
        "Bardzo ładna panorama Gdańska. Gdy jest ładna pogoda... To trzeba samemu zobaczyć;).\r\nTrzeba wejść po schodach, a całkiem jest ich sporo.",
        2, 1),
       ( 5
       , "Super duży park, mnóstwo ciekawych miejsc, stawy, rzeka, palmiarnia, muzeum i wiele więcej. Wspaniałe miejsce na odpoczynek i rodzinny spacer, szerokie alejki i co krok ławeczki. Wizyta w katedrze obowiązkowa, ciekawe żebrowe sklepienie, oszczędne zdobione, jasne wnętrze o ile się nie mylę to najdłuższy kościół w Polsce. No i oczywiście sławne organy :) W niedzielę o 15.00 odbywa się krótki 20 minutowy koncert - można posłuchać potęgi dźwięku tego ''instrumentu''."
       , 3, 1),
       ( 4
       , "Ładny park, zazwyczaj zadbany - czy to zasługa odwiedzających, czy pracowników, że po ziemi nie walają się poruszane wiatrem śmieci - nie rozstrzygam. Nie ma toalety dla turystów i spacerowiczów - i to jest ogromny minus (toalety czynne tylko w konkretnych godzinach znajdują się po drugiej stronie ulicy i przy dworcu kolejowym, aczkolwiek w parku nie ma oznaczeń, w którą stronę się do nich kierować). Wiosną przepięknie kwitną magnolie i japońskie wiśnie. Od kilku lat jest też cały Ogród(ek) Japoński, ulokowany przy wejściu do ogrodu Doraco. I do jednego, i drugiego ogrodu również warto zajrzeć - w tym drugim jest fontanna i jakże nostalgiczna rzeźba zamyślonej poetki."
       , 3, 1),
       ( 4
       , "Super park. Jest on bardzo duży i posiada piękny, dobrze wygospodarowany krajobraz.\r\nSpacerowanie po nim jest czystą przyjemnością i można poczuć się jak odkrywca jakiegoś opuszczonego, zaginionego ogrodu. Oprócz tego są tam muzeum sztuki nowoczesnej, stawy, rzeki i szereg różnych rzeźb i pomników. Polecam."
       , 3, 1),
       ( 3
       , "Super miejsce na lato, jest dużo cienia. Na miejscu mozna wypić kawę i coś przekąsić. Natomiast minusik bo dla dzieciaków nie ma placu zabaw :("
       , 3, 1),
       ( 4
       , "Przepiękne malownicze miejsce, zdobione przez kolorowe kamieniczki i budynki. W okresie Świątecznym, Bożonarodzeniowym to miejsce jest jeszcze piękniejsze, rozświetlone od blasku lampek, choinki, atrakcyjnych lokali gdzie można napić się ciepłej ,,zimowej herbaty\" czy zjeść coś dobrego na ząb.\r\nFontanna Neptuna to niewątpliwie najbardziej rozpoznawalny i obowiązkowy punkt do odwiedzenia w Gdańsku. Warto przejść się wzdłuż ciągnących kamienistych dróżek, by podziwiać te wspaniałe obiekty. Architektura w tej okolicy jest wyjątkowo piękna i zdobnicza, przyciąga oko.\r\nNiedaleko warta do odwiedzenia Bazylika konkatedralna Wniebowzięcia Najświętszej Maryi Panny  inaczej przezywną Bazyliką Mariacką.\r\nWcale nie wygląda na tak kolosalną jak w rzeczywistości jest. Główne wejście do bazyliki jest od ulicy Piwnej. By zobaczyć jej monumentalność warto obejść ją dookoła od wszystkich stron, chociażby po to by zobaczyć zegar astronomiczny  wykonany przez Hans Düringera z Torunia. Naprawdę jest to godne polecenia miejsce."
       , 5, 1),
       ( 4
       , "Przepiękne malownicze miejsce, zdobione przez kolorowe kamieniczki i budynki. W okresie Świątecznym, Bożonarodzeniowym to miejsce jest jeszcze piękniejsze, rozświetlone od blasku lampek, choinki, atrakcyjnych lokali gdzie można napić się ciepłej ,,zimowej herbaty\" czy zjeść coś dobrego na ząb.\r\nFontanna Neptuna to niewątpliwie najbardziej rozpoznawalny i obowiązkowy punkt do odwiedzenia w Gdańsku. Warto przejść się wzdłuż ciągnących kamienistych dróżek, by podziwiać te wspaniałe obiekty. Architektura w tej okolicy jest wyjątkowo piękna i zdobnicza, przyciąga oko.\r\nNiedaleko warta do odwiedzenia Bazylika konkatedralna Wniebowzięcia Najświętszej Maryi Panny  inaczej przezywną Bazyliką Mariacką.\r\nGdańsk to miejsce,którego nie trzeba szczególnie zachwalać,to miejsce znane nie tylko w kraju. Sam spacer po Długim Targu wśród cudownych kamienic wprawia w zachwyt. Fontanna Neptuna Dwór Artusa i Żuraw to sztandarowe miejsca starego miasta.Do tego muzea,galerie ...no i można posłuchać pięknej muzyki w bramie nad Motławą. Staram się odwiedzać Gdańsk tak często jak to możliwe i za każdym razem odkrywam na nowo to cudowne miasto."
       , 5, 1),
       ( 4
       , "Przepiękne malownicze miejsce, zdobione przez kolorowe kamieniczki i budynki. W okresie Świątecznym, Bożonarodzeniowym to miejsce jest jeszcze piękniejsze, rozświetlone od blasku lampek, choinki, atrakcyjnych lokali gdzie można napić się ciepłej ,,zimowej herbaty\" czy zjeść coś dobrego na ząb.\r\nFontanna Neptuna to niewątpliwie najbardziej rozpoznawalny i obowiązkowy punkt do odwiedzenia w Gdańsku. Warto przejść się wzdłuż ciągnących kamienistych dróżek, by podziwiać te wspaniałe obiekty. Architektura w tej okolicy jest wyjątkowo piękna i zdobnicza, przyciąga oko.\r\nNiedaleko warta do odwiedzenia Bazylika konkatedralna Wniebowzięcia Najświętszej Maryi Panny  inaczej przezywną Bazyliką Mariacką.\r\nNeptun słabo podświetlony, wieczorem i w nocy bez rewelacji - może miasto oszczędza energię. Mnóstwo ludzi w pobliżu."
       , 4, 1),
       (5,
        "Szczerze nie rozumiem hejtu na obsługę, a może nam po prostu trafił się mega shift, bo z Paniami można było sobie pożartować i się pośmiać. Czas oczekiwania faktycznie długi, ale pierogarnia o tym ostrzega. Z resztą wolę poczekać i mieć świeże jedzonko niż szybko dostać coś rozmrażanego.\r\nMoim największym problemem zawsze jest jak spróbować innych pierogów skoro te, które wcześniej brałam były idealne i ostatecznie zawsze zamawiam te same :<\r\n5\/5, wspomnę tylko jeszcze, że macie dobre piwo i koszulki są dobrej jakości. Rzadko bywam w Trójmieście, ale wracam za każdym razem❤",
        5, 1),
       (3,
        "Szczerze nie rozumiem hejtu na obsługę, a może nam po prostu trafił się mega shift, bo z Paniami można było sobie pożartować i się pośmiać. Czas oczekiwania faktycznie długi, ale pierogarnia o tym ostrzega. Z resztą wolę poczekać i mieć świeże jedzonko niż szybko dostać coś rozmrażanego.\r\nMoim największym problemem zawsze jest jak spróbować innych pierogów skoro te, które wcześniej brałam były idealne i ostatecznie zawsze zamawiam te same :<\r\nZacznę od samych pierogów - okazały się średnie, ciasto bardzo smaczne ale z tego co widać na zdjęciu tylko chinkali były wyjątkowe. Wypełnienie pierogów miesiąca - pieczarki z serem i salami to tak na prawdę same pieczarki i tu największe rozczarowanie - te pierogi były niesmaczne. Pierogi mistrzów z szyjkami rakowymi całkiem w porządku ale czegoś im brakowało. Kelner proponuje surówki ale nie informuje, że są ekstra płatne. Na plus duży wybór fajnego piwa. Jest strefa zabaw dla dzieci. Obsługa bardzo miła. Ocena 3\/5 przez przereklamowany smak pierogów. Lokal cieszy się ogromną popularnością, długi czas oczekiwania na posiłek, ale można to sobie wypełnić smaczną zupą. Ogólna ocena to - miało być wow, a było tak sobie. Wrócę niespiesznie",
        5, 1),
       (5,
        "Szczerze nie rozumiem hejtu na obsługę, a może nam po prostu trafił się mega shift, bo z Paniami można było sobie pożartować i się pośmiać. Czas oczekiwania faktycznie długi, ale pierogarnia o tym ostrzega. Z resztą wolę poczekać i mieć świeże jedzonko niż szybko dostać coś rozmrażanego.\r\nMoim największym problemem zawsze jest jak spróbować innych pierogów skoro te, które wcześniej brałam były idealne i ostatecznie zawsze zamawiam te same :<\r\nMoje jedno z ulubionych miejsc w Gdańsku jak chyba wielu osób, gdyż niejednokrotnie trzeba było czekać w kolejce, ale warto! Bardzo miła obsługa, zawsze doradzi co do wyboru pierogów, czas oczekiwania 20-30min, pierogi przepyszne, nigdy się nie zawiodłem, polecam!",
        5, 1),
       (1,
        "Nie polecam!!!! Zamówiliśmy apartament na 12 piętrze a dostaliśmy na 8 piętrze, gdyż właściciel dolicza do pięter, trzy poziomy parkingu podziemnego i parter. Apartament miał być z widokiem na zatokę, był ale po wychyleniu się, a z okna to widok na przeciwną wieżę budynku. Ponadto po klucze do apartamentu trzeba było jechać do pani na ul. Kcyńską, brak osoby odpowiedzialnej w budynku. Sam apartament to porażka, ściany odrapane i jak po bitwie, meble stare i brudne, a pościel to sprzed 20-u laty. Ogólnie czysto, lecz wnętrze nieciekawe. Zostaliśmy oszukani i czujemy niesmak. Nie polecam!!!",
        6, 1),
       (5,
        "Wspaniały widok na morze, można się w nie wpatrywać. Pokoje całkiem duże, czyste,  cisza spokój i wszędzie blisko.",
        6, 1),
       (5,
        "Polecam! Zdecydowanie lepsza miejscówka niż Molo w Sopocie. W mojej opinii większe, wygodniejsze do spacerów. Ma swój urok, mniej ludzi w okolicy i na samym molo, zdjęcia wychodzą świetnie, a w okol sporo ciekawych ścieżek do spacerowania. Dojazd znakomity, restauracja obok. Naprawdę super miejsce :)",
        7, 1),
       (5,
        "Bardzo ładne miejsce. Zdecydowanie przyjemniejsze niż molo w Sopocie. Trzeba korzystać, póki jeszcze można, ponieważ już znaczna część okolicznych terenów została wyprzedana deweloperom. Od mola można przejść plażą do Sopotu i dalej; w drugą stronę można kiedyś było było dojść przez Polankę Redłowską do gdyńskiego bulwaru i tamtejszej miejskiej plaży - teraz, być może, ominięcie klifu jest niemożliwe. Samo molo jest w bardzo dobrym stanie technicznym. Nie ma jednak w pobliżu toalety dla turystów.",
        7, 1),
       (4,
        "Bardzo piękne, nieduże molo, miejsce, w którym poczujesz się jak bohater książki. Patrzysz na wzgórze i myślisz, może tu Asol stała i czekała, ale\u2026 Świetne miejsce, by cieszyć się naturą, być z samym sobą, a spacer wzdłuż morza jest niezrównany, orzeźwiający i pełen energii. Polecam spacer, nie musisz cały czas jeździć, zrozum, że nasze zdrowie i nasze ręce cieszą się naturą.",
        7, 1),
       (5,
        "To miejsce mnie przyciągnęło( prawie 500km od niego samego) .\r\nPrzyjechałam, zobaczyłam, zakochałam się bardziej i zapragnęłam mieszkać bliżej by móc to odwiedzać częściej i cieszyć się pięknymi widokami  \r\nKiedy ma się szczęście może zachwycić nie tylko kolorami poranku gdy wschodzi słońce nad choryzont, ale też barwy zachodu mogą ucieszyć oko.",
        8, 1),
       (5,
        "To miejsce mnie przyciągnęło( prawie 500km od niego samego) .\r\nPrzyjechałam, zobaczyłam, zakochałam się bardziej i zapragnęłam mieszkać bliżej by móc to odwiedzać częściej i cieszyć się pięknymi widokami  \r\nPrzepiękne miejsce, cudne widoki, ogrom możliwości spacerowania, biegania czy jazdy na rowerze! Uważam tylko, iż należałoby zmodernizować trochę zabezpieczenia skraju kilfu. Mowa tutaj o pewnego rodzaju barierkach, które mocno poprawiłby bezpieczeństwo oraz komfort spacerujących tu turystów. Nie jest to duży koszt, a naprawdę zrobiłby różnicę i wpłynął na podwyższenie jakości tego wspaniałego miejsca!",
        8, 1),
       (5,
        "To miejsce mnie przyciągnęło( prawie 500km od niego samego) .\r\nPrzyjechałam, zobaczyłam, zakochałam się bardziej i zapragnęłam mieszkać bliżej by móc to odwiedzać częściej i cieszyć się pięknymi widokami  \r\nSuper miejsce na wycieczkę ✌️ Piękna trasa lasem z plaży przy Tawernie obok mola w Orłowie, przez punkt widokowy, klify aż do zejścia na plaży gdzie znajduje się bunkier i powrót plażą pod Tawernę zajmuje spokojnym spacerem z dzieckiem 4,5 lat ok godziny. Ostrzegam jednak że można się \"zawiesić\" i spędzić na górze dużo więcej czasu podziwiając widoki i pływające statki 😁✌️",
        8, 1),
       (4,
        "To miejsce mnie przyciągnęło( prawie 500km od niego samego) .\r\nPrzyjechałam, zobaczyłam, zakochałam się bardziej i zapragnęłam mieszkać bliżej by móc to odwiedzać częściej i cieszyć się pięknymi widokami  \r\nPo zejściu w dół idąc plażą klify wyglądają jakby miały razem z drzewami za chwilę się oderwać. Niesamowite widoki ✌️",
        8, 1),
       (5,
        "Warto odwiedzić by poznać historie tego niezwykłego statku. Muzeum nie jest duże ale   umożliwia niezwykła podróż w przeszłość by zobaczyć jak mieszkali marynarze, gdzie jedli spali i jak wyglądała ich codzienność. Inspirujące historie opowiadaja osoby dbające o porządek w muzeum wystarczy odrobina zainteresowania.",
        9, 1),
       (3,
        "Takie muzea były ok w XX wieku tzn. eksponaty, do tego tekst i tyle. Z podróży po tym statku nie da się zapamiętać nic ciekawego.",
        9, 1),
       (3,
        "Długo zbieraliśmy się żeby w końcu zjeść w Neonie. Zawsze coś nam wypadało i nie mogliśmy tam trafić, może i dobrze, bo niestety jedzenie nas nie zachwyciło... Zupa za słona. Phad thai o smaku spalenizny nie porwał. Na bardzo duży plus obsługa za równo na barze jak i na sali, klimat fajny, tylko to jedzenie nie takie :( Może jeszcze wrócimy, żeby dać drugą szansę...",
        10, 1),
       (4,
        "Jedzenie ok, smaczne,. Nie czeka się zbyt długo. Duży wybór lemoniad (ale nie są to lemoniady takie typowe swieżo wyciskane) szkoda.Wystroj przecietny, trochę chłodny. Obsluga miła. Ceny średnie. Porcje duże.\r\nMyślę, że z czystym sumieniem mogę polecić.",
        10, 1),
       (5, "Moje ulubione miejsce w Gdyni. Najlepsze kanapki z tatarem, tataki z tunczyka i piwo imbirowe :)", 10, 1),
       (4,
        "Warto odwiedzić będąc w Warszawie , natomiast w dobie pandemii , tłumy na wieżę widokową. Mimo obsługi nikt nie piknuje dystansu , z windą to samo każdy wchodzi jak chce. Sama wieża widokowa super , można zobaczyć Warszawę z każdej strony. Polecam szczególnie nocą ,robi wrażenie !",
        11, 1),
       (5,
        "podczas ostatniego pobytu w Warszawie tylko przechodziłam obok PKiN, bo w sumie.. po co wchodzić. 🤦🏻\u200D♀️ dzisiaj przyjechałam do stolicy głównie ze względu na niego. i trafiłam idealnie. Narodowe Muzeum Techniki - jak się okazuje, we wtorki wstęp za darmo. duuużo informacji na wszelakie tematy - zaczynając od komputerów, kończąc na samolotach. polecanko.\r\nwstęp na taras widokowy - 20zł za piękny widok, zrobienie fotek i szybką jazdę windą na trzydzieste piętro.\r\nna Muzeum Ewolucji nie zdążyłam, ale jutro zamierzam się tam wybrać.",
        11, 1),
       (2,
        "Wiele razy odwiedziłam to miejsce i z przykrością muszę stwierdzić, że z każdą wizytą czuję się zniechęcona do przebywania w tym miejscu.\r\nWystawy same w sobie są jak najbardziej ciekawe, ale ceny i regulamin muzeum pozostawia wiele do życzenia. Moim zdaniem ceny za bilety (szczególnie za wystawy czasowe) są bardzo nieadekwatne. Po drugie obsługa zamku jest źle nastawiona na turystów. Starsze panie pilnujące sal traktują zwiedzającego jako złodzieja i gorszego od nich. Na wystawach nie można zawracać, to znaczy jeśli przejdziesz do innej sali to do poprzedniej już nie wrócisz \"bo taki regulamin\". Osoby które mają nakazane poruszanie się z kijkami też nie są dobrze widziane, ponieważ wnoszenie jakichkolwiek kijków na wystawę jest zakazane. Jest mi bardzo przykro, że nikt jeszcze nie zareagował w sprawie tego regulaminu i przestarzałej kadry.",
        12, 1),
       (5, "Super miejsce, polecam wszystkim", 12, 1),
       (4,
        "Wiele razy odwiedziłam to miejsce i z przykrością muszę stwierdzić, że z każdą wizytą czuję się zniechęcona do przebywania w tym miejscu.\r\nWrażenia super. Piękne wnętrza. Szkoda, że tak mało się zachowało. Na zamku można robić zdjęcia. Jest sklepik z pamiątkami, a także audioprzewodnik. Zwiedzanie sal królewskich zajęło nam około godziny.",
        12, 1),
       (4,
        "Wiele razy odwiedziłam to miejsce i z przykrością muszę stwierdzić, że z każdą wizytą czuję się zniechęcona do przebywania w tym miejscu.\r\nZamek królewski i kolekcja jaką posiada zapiera dech w piersiach. Rembrant , Matejko,Canaletto, Baciarelli +czasowa wystawa Caravaggio   Polecam wykupić audioprzewodnik koszt 10 złotych a zupełnie inna jakość zwiedzania. Dzieł sztuki sal, pokoi jest tak dużo ,że oglądanie ich bez odpowiednich informacji moim zdaniem nie ma sensu. A jest sporo ciekawostek. Ochrona natomiast w pokojach a zwłaszcza w galerii arcydzieł traktuje ludzi jak bydło. Totalne chamstwo zwłaszcza po damskiej stronie. Kilka Pań pracuje zapewne za darmo stąd frustracja i wyrzucanie swoich złości na zwiedzających. Dziwię się bo Warszawa taka duża można znaleźć pracę płatna.",
        12, 1),
       (5,
        "Bardzo piękne miejsce , bardzo kolorowe dzięki rozciągającym się po środku dywanem ślicznych kwiatów z centralnym punktem majestatycznej  bardzo widowiskowej fontanny .\r\nOdpowiednie miejsce aby usiąść na ławeczce i odpocząć po zwiedzaniu stolycy , szybko nabierzesz siły przed kolejnymi celami.",
        13, 1),
       (5,
        "Bardzo piękne miejsce , bardzo kolorowe dzięki rozciągającym się po środku dywanem ślicznych kwiatów z centralnym punktem majestatycznej  bardzo widowiskowej fontanny .\r\nMyślę, że szczególnie przez wzgląd na Grób Nieznanego Żołnierza jest to szczególne miejsce, które koniecznie należy zobaczyć podczas wizyty w Warszawie. Byłem tam na obchodach narodowego święta  niepodległości w listopadzie więc ogród nie zachwycił pięknem barw i fontanną.",
        13, 1),
       (5,
        "Piękna pogoda i pieknw miejsce mimo iż jest 12.02 to słońce świeci i wszystkie atrakcje są dostępne tak że można spokojnie zwiedzać i cieszyć się naturą. Teatr na wodzie pewnie z aktorami wygląda bajecznie. Pałace w środku pewnie też, ale dziś tylko spacer do koła wody. Spacer na górkę aby zobaczyć pomnik sławnego kompozytora Chopena. Wszystko w słońcu i przy towarzystwie wiewiórek. Polecam bo to obowiązkowy punkt  na mapie Warszawy dla każdego turysty.",
        14, 1),
       (5,
        "Piękny park, pełen starych dużych drzew. Doskonale miejsce na spacery nawet w upalne dni. Cudowny zespół pałacowo - ogrodowy. Trzeba zobaczyć, pospacerować nacieszyć oko wiewiorkami, które nie boją się ludzi a nawet wydają się pozować do zdjęć. Oczywiście należy odpocząć chwilę na ławeczce i podziwiać pomnik Chopina. Polecam dla dużych i małych.",
        14, 1),
       (2, "Może być", 14, 1),
       (5,
        "Jedno z najsłynniejszych miejsc w stolicy. Bardzo dobry dojazd metro.  Piekny pomnik z pięknym widokiem na most Świętokrzyski oraz stadion. W okręcie letnim dodatkowo atrakcją dla dzieci - fontanny dla schłodzenia.  Warto przejść się bulwarami",
        15, 1),
       (5,
        "Fajne miejsce na chwilkę rekreacji. Podczas upałów uruchamiane są mgiełki wmontowane  w chodnik. Ładny widok na Wisłę, stadion i Most Świętokrzyski. Super że można podjechać pod Syrenke metrem.",
        15, 1),
       (4,
        "Miejsce ważne do zobaczenia. Zawsze chciałam na własne oczy ujrzeć pomnik syrenki. Trochę jednak mnie rozczarował,  może nie był tak duży,  jak moje wyobrażenie o nim. Dużo ludzi się  kręci,  taki urok miejsca. Obok pomnika zraszacze, w upalne dni można skorzystać z ochłody. Niestety woda z jednej z części śmierdzała szambem.",
        15, 1),
       (5,
        "Od razu powiem, że zwykle nie jem brzegów w pizzę, ale tu zjadam absolutnie wszystko nie pozostawiając nic na talerzu :)\r\nWyjątkowa karta, pyszne składniki i połączenia. Niektóre połączenia smaków są dosyć niezwykłe, ale baaardzo pyszne. Bardzo mi smakowała pizza z puree ziemniaczanym, mortadellą i orzeszkami - nigdy czegoś takiego nie próbowałam. Margheritę na co dzień nie wybieram, ale tu nawet taka \u201Epodstawowa i klasyczna\u201D pizza jest po prostu obłędna, zjadam za sekundę!! :) Obowiązkowo spróbujcie!\r\nNo i last, but not least: ludzie - tu pracują super cudowni, uśmiechnięci i pozytywni! <3",
        16, 1),
       (2, "Czy warto było czekać na ten stolik? Długi okres oczekiwania.", 16, 1),
       (4,
        "Jakoś tak wyszło, że długo zwlekałem z pierwszą wizytą. Nie składało się. W końcu jednak trafiliśmy na neapolitańsķą pizzę do Pizzaiolo.\r\nJedzenie jest smaczne, ale ta pizza jest inna niż te, do których przywykłem. Ciasto jest miękkie i puszyste mimo że dobrze wypieczone. Widać że wszystko jest robione z należytą starannością a składniki świeże i wysokiej jakości. Smak to kwestia gustu, Polecam spróbować. Dla mnie trochę za miękko, zbyt puszyście i w przypadku foccacia jednak ciut za tłusto.\r\nInna rzecz to klimat lokalu. Jest tu nowocześnie i rockowo ale dla mnie muzyka jest nieco za głośna i nie polecam wybierać lokalu na długie lub ważne rozmowy- jest głośno. Tak pewnie miało i ma być, bo wynika to ze specyfiki miejsca.\r\nPyszne napary ziołowe zamiast herbaty to świetny pomysł,  gorzej z blaszanymi kubkami, które dość mocno się nagrzewają i parzą w dłonie",
        16, 1),
       (3,
        "Miejsce, które \"ślizga się\" wciąż przez pryzmat sławy i historii, choć wiele miejsc bije Wawel o głowę historycznie. Za zwiedzanie każdego miejsca trzeba płacić osobno, a szkoda, że nie sprzedają biletu na zwiedzanie całości. Podaje ceny za bilet normalny. Zdecydowałam się na prywatne apartamenty-kilka komnat (25 zł), ogrody królewskie (5 zł) i smoczą jamę (9 zł). Niestety nic ciekawego.... To, co mnie najbardziej interesowało, było zamknięte ze względu na remont. Natomiast warto obejrzeć teren wokół, wstęp bezpłatny.",
        17, 1),
       (5,
        "Mój ulubiony zamek, a właściwie całe wzgórze wawelskie 😉. Wejście na dziedzińce za darmo w godzinach otwarcia wzgórza, wejścia na poszczególne wystawy\/ekspozycje płatne. Kasy znajdują się: tuż za bramą, przy wejściu od ulicy Kanoniczej oraz w budynku dawnych koszar. W sezonie kolejki do kas są spore, najlepiej zakupić bilety przez internet, oczywiście z wyprzedzeniem bo np. do komnat królewskich można nie dostać na ostatnią chwilę. Kasa katedry jest osobno i znajduje się w budynku na przeciwko wejścia do katedry. Płacić można kartą, są toalety, restauracja, sklepik z pamiątkami.",
        17, 1),
       (3,
        "Zbiory muzeum należą do największych i najpiękniejszych jakie widziałem.\r\nALE!!! Odnoszę wrażenie że jest to fabryka turystów i wyciągania od nich pieniędzy. Wejście do każdego miejsca jest płatne osobno. Pomimo kilkukrotnego zapytania czy istnieje możliwość zwiedzenia z audio przewodnikiem lub aplikacją, nikt przy kasie lub informacji nie wspomniał, że można zwiedzać z przewodnikiem w grupie. Dopiero kiedy sami wspomnieliśmy o tej opcji, to dowiedzieliśmy się że co 1,5h są wejścia do komnat reprezentacyjnych i apartamentów prywatnych. Lecz widzieliśmy także grupy które zwiedzały zbrojownię. Zdążyliśmy jednak już obejść wymieniane komnaty sami, patrząc na eksponaty jak \"łosie\" : O krzesło, o szafa, o talerz, o dywan na ścianie. Bez żadnej historii. Zwiedzanie nie zajęło nam 1,5h lecz 45 min i zrobiliśmy miejsce dla kolejnych turystów. Poza tym sugeruję zwiedzać Wael poza sezonem lub deszczowe dni, bo inne zabytki Krakowa są zbyt piękne żeby tracić czas pod dachem. Pomimo wszystko wrócę tu jeszcze bogatszy o swoje doświadczenia, może wtedy wyjdę z mniejszym niesmakiem i niedosytem.",
        17, 1),
       (5,
        "Zbiory muzeum należą do największych i najpiękniejszych jakie widziałem.\r\nPiękne miejsce, obowiązkowy punkt podczas wizyty w Krakowie.\r\nOznaczenia są ale mogły by być lepsze i do przydałyby się tablice informacyjne zamiast stać w gigantycznej kolejce",
        17, 1),
       (5,
        "Będąc w Krakowie i spacerując po jego Rynku Głównym trudno jest nie zauważyć wydłużonego budynku dzielącego plac na dwie równe części. To najstarsze krakowskie",
        18, 1),
       (5,
        "W centrum Krakowa na rynku mieszczą się Sukiennice, miejsce z niezwykłą historią.\r\nWewnątrz jest atmosfera targowa, gdzie jest pełno małych kramów z różnymi gadżetami do kupowania.\r\nNatomiast na zewnątrz mieszczą się kawiarnię, cukiernie i lokalne gastronomiczne a na piętrze jest ulokowane muzeum do zwiedzania.\r\nNa pewno każdy znajdzie coś dla siebie w to nie można wątpić. Nieopodal stoi bardzo dobrze wszystkim znany Kościół Mariacki 😃\r\nPięknie jest siedzicie pod pomnikiem A. Mickiewicza wsłuchując się w grany hejnał z wieży 😃",
        18, 1),
       (5,
        "W centrum Krakowa na rynku mieszczą się Sukiennice, miejsce z niezwykłą historią.\r\nWewnątrz jest atmosfera targowa, gdzie jest pełno małych kramów z różnymi gadżetami do kupowania.\r\nNatomiast na zewnątrz mieszczą się kawiarnię, cukiernie i lokalne gastronomiczne a na piętrze jest ulokowane muzeum do zwiedzania.\r\nNa pewno każdy znajdzie coś dla siebie w to nie można wątpić. Nieopodal stoi bardzo dobrze wszystkim znany Kościół Mariacki 😃\r\nKrakowskie sukiennice to nieodłączny wizerunek rynku. Są jednym z zabytków, który jednoznacznie kojarzy się z Krakowem. Handel w tym miejscu odbywał się od wieków, jednak obecny wygląd sukiennic znacznie odbiega od tych pierwotnych. Sukiennice powstały w 1358 r. Oczywiście od tamtego czasu sporo się zmieniły. Obecnie możemy tu kupić głównie pamiątki i rękodzieło. Na pietrze znajduje się oddział muzeum narodowe. W Sukiennicach zaczyna się także podziemna trasa zwiedzania pod rynkiem. Myślę, że każdy kto był w Krakowie natchnął się na sukiennice.",
        18, 1),
       (5, "Idealne miejsce na spacery. Piękne, ukwiecone, cieniste i spokojne.", 19, 1),
       (5,
        "Miejsce bardzo charakterystyczne dla Krakowa. Planty, to wąski park otaczający starówkę, powstały podczas zagospodarowania terenów pozostałych po dawnych fortyfikacjach. Ulubione miejsce spacerów zarówno mieszkańców, jak i turystów.",
        19, 1),
       (5, "Bardzo ładne miejsce do wybrania się na spacer, ciekawe zabytki w okolicy.", 19, 1),
       (2, "Nie Polecam!", 20, 1),
       (5,
        "Jest to jedna z droższych restauracji w których bywam, ale zdecydowanie warta swojej ceny. Zacznę od najsłabszej pozycji którą zamówiliśmy, przystawki tj. borowików. Były bardzo smaczne jednak dość mało odkrywcze (chociaż przez cały czas jedzenia nie mogliśmy rozpoznać co nadaje im taki fajny posmak). Kolejne pozycje były już strzałami w 10. Policzki wołowe i golonka były wyśmienite. Jeśli ktoś lubi konkretny kawałek mięsa to golonka jest obowiązkowa. Chrupiąca skórka, do niej pyszna kapusta, nawet puree ziemniaczane było wyjątkowo smaczne. W policzkach wołowych podano przepyszne dodatki. Do tego bardzo smaczne nalewki które są obowiązkowe do obiadu.",
        21, 1),
       (5,
        "Od czawgo by tu zacząć... Generalnie jedzenie jest wyśmienite. Z racji złego samopoczucia nie mogłem wraz z mam udać się na miejsce, więc zamówiliśmy przez glovo. Jedzenie przyszło ciepłe i świeże. Na przystawkę zamówiliśmy zupę dnia oraz 10 pierożków ze szpinakiem. Zupą okazał się barszcz który był wyśmienity. Zblendowany na krem wraz z nasionkami słonecznika robił robotę. Pierogi też super. Szpinak dobrze doprawiony a dzięki serkowi farsz był niezwykle kremowy. Na główne dania poleciał burger oraz policzki wołowe. Burger był tak dobry, że nie pamiętam kiedy ostatnio takiego jadłem. Mięso soczyste i perfekcyjnie usmażone oraz dobry ciągnący się cheddar. Reszta składników też super. Sos czosnkowy też super, chyba autorski. Frytki jak frytki - spoko. Policzki były także bardzo dobre. Mięso zarówno kruche jak i rozpadające się w ustach. Warzywa do tego były idealnym dodatkiem. Restauracji nie mam nic do zarzucenia. Mogę polecić w 100 procentach. Pozdrawiam",
        21, 1),
       (5,
        "Przepyszne miejsce w Krakowie. Na pewno tu wrócę. Obsługa bardzo miła, profesjonalna, szybka i dokładna. Wszystko było smaczne: pierogi, policzki, poledwiczka. Ładnie podane aż jadło się oczami! Nalewki- duży wybór smaków i warto popróbować:) polecam!",
        21, 1),
       (5,
        "Panorama Racławicka autorstwa Jana Styki i Wojciecha   Kossaka namalowana we Lwowie w 1894 roku w setną rocznicę powstania Kościuszkowskiego.\r\nOglądając panoramę odnosi się wrażenie,  jakbyśmy uczestniczyli w bitwie ukazane na obrazie, a głos lektora i dźwięki z pola bitwy potęgują te wrażenia. Efekt jest niesamowity. A otoczka samego obrazu w postaci krzaków skał, piasku , czy porzuconej broni daje niesamowity efekt 3D obrazu, zacierajac połączenie płótna z naturalną otoczka wokół . Bilet kosztuje  50 zl, ale.naprawdę warto, gdyż oprócz półgodzinnego spektaklu oglądając Panoramę Raclawicką, możemy przez okres trzech miesięcy odwiedzić w ramach biletu trzy następne obiekty , w tym między innymi Muzeum Narodowe.  Ja polecam , bo naprawdę warto.",
        22, 1),
       (5,
        "Panorama Racławicka autorstwa Jana Styki i Wojciecha   Kossaka namalowana we Lwowie w 1894 roku w setną rocznicę powstania Kościuszkowskiego.\r\nRotunda i Panorama Racławicka znajdują się w parku Słowackiego. \u201EBitwa pod Racławicami\u201D ukazuje bitwę stoczoną 4 kwietnia 1794 roku przez wojska powstańcze z udziałem kosynierów pod wodzą generała Tadeusza Kościuszki z wojskami rosyjskimi dowodzonymi przez generała Aleksandra Tormasowa. Niezwykłość obrazu \u201EBitwa pod Racławicami\u201D jest wynikiem ukazanej panoramy, gry świateł i wielowymiarowości dzieła. Sprawia to, że obraz zdaje się być stworzonym za pomocą współczesnej technologii. Niesamowity obraz. Wielkość obrazu jak i jego \"naturalność\" robi niesamowite wrażenie.\r\nTrójwymiarowość inscenizacji, mnogość szczegółów, sprawia wrażenie rzeczywistości wydarzeń. Naprawdę to robi wrażenie. Uważam to za jedną z ikon Wrocławia. Jedna z nielicznych atrakcji, która jest obowiązkowo do zobaczenia!\r\nDodatkowa wystawa - mała rotunda - prezentacja multimedialna. Jest też sklepik z pamiątkami, nie tylko dotyczącymi panoramy racławickiej.",
        22, 1),
       (5,
        "Bardzo urokliwe miejsce w mieście Wrocław znajdujące się nieopodal ogrodu zoologicznego oraz parku z fontannami multimedialnymi. Bardzo dobrze zaprojektowany świetnie utrzymany z typowym dla orientu wschodniego sznytem i klasa. Świetny na spacer i do kontemplacji. Przerażające jest to że XXI wiek zawitał i nie ustawiono biletomatu, nie można kupić biletów przez internet tylko trzeba stać w wężowej kolejce by zakupić bilet wejścia do ogrodu. To przykre że w takim mieście jak Wrocław czas się zatrzymał. Choć sam ogród jest klimatyczny i urokliwy to jednak czekanie na słońcu w wężowej kolejce jest zniechęcające.  Polecam wszystkim odwiedzenie tego miejsca jednak po bilety warto przyjechać wcześniej",
        23, 1),
       (5,
        "Ogród mi się podobał, choć spodziewałam się, że będzie większy? I troszkę się zawiodłam, że było mało kolorowych kwiatów, a więcej zieleni, ale to zapewne przez to, że mamy już wrzesień...Pomimo, że jest dalej ciepło, to wnioskuje po zdjęciach z poprzednich miesięcy, że lepiej jest się wybrać bliżej wiosny do ogrodu albo gdzieś w okolicach czerwca\/lipca bądź sierpnia. Ale nie żałuję, zwłaszcza, że odwiedziłam ogród w niedzielę i była kolejka, aczkolwiek kasa się zepsuła i wszyscy wchodzili bez płacenia, także miałam wejście za darmo :D Zaraz obok ogrodu znajduje się hala stulecia, pelgora i fontanna, które zrobiły na mnie duże wrażenie, może nawet i większe niż sam ogród. Piękne widoki, polecam się tam wybrać, można zrobić naprawdę fajne zdjęcia :)",
        23, 1),
       (4,
        "Wrocławski Ogród Japoński to miejsce bardzo oblegane przez turystów. Gdy jednak tam dotarliśmy, wyjątkowo nie było żadnej kolejki i udało nam się wejść od razu (godz. 17:30). Co do samego ogrodu - wejściówka mogłaby być troszkę tańsza (bilet normalny to koszt 15 zł), szczególnie biorąc pod uwagę rozmiar tego miejsca (ogród nie jest specjalnie duży... ale nie jest też jakiś bardzo mały, ot atrakcja na jakieś 30 minut - włącznie z robieniem zdjęć).",
        23, 1),
       (5,
        "Zakochałam się w tym miejscu! Piękny rynek, urzekły mnie te kolorowe budynki, które były dosłownie wszędzie, bardzo ładnie się to prezentuje na zdjęciach jak i na żywo. Duży wybór restauracji (co prawda większość z nich jest bardzo droga, jak to w centrum i w tak popularnym miejscu), ale oceniając rynek, skupiam się bardziej na stronie wizualnej. Również piękny kościół i fontanna. Warto się przejść, żeby sobie pozwiedzać, pospacerować, porobić zdjęcia. Czasem można zaszaleć i wejść do jakiegoś sklepu czy zjeść w restauracji, nawet jeśli jest droższa :) Polecam również sklep Candy Cat, który znajduje się na rynku, mają tam dobre słodycze, całkiem spory wybór słodkości i bardzo ładny wystrój, choć ceny też oczywiście są spore, więc trzeba się z tym liczyć.",
        24, 1),
       (5,
        "Piękny i jeden z największych Starych Rynków w Polsce (w top 5 największych polskich Rynków). Z niesamowitym starym ratuszem i tym \"trochę\" nowszym, z pięknymi odrestaurowanymi kamienicami. Z dużą ilością fajnych restauracji, pubów, lokalnym browarem. Z niesamowitym klimatem, a w okolicach Świąt Bożego Narodzenia z klimatycznym i ciekawym jarmarkiem bożonarodzeniowym. Chciałoby się tu być ciągle, spacerować i delektować oczy tymi widokami i cieszyć duszę tym klimatem. Jak na razie mój numer 1 w Polsce, tj. Rynek (a widziałem już kilka). POLECAM to miejsce, następnym razem zatrzymamy się w hotelu na samym Rynku (których też jest kilka), żeby też wieczorem poczuć klimat tego miejsca.",
        24,1),
       (5,
        "Most który zawsze jest ciekawym obiektem do fotografowania, bez względu na porę roku. Warto zobaczyć to miejsce samemu będąc we Wrocławiu, pochodzić i poznać okolice.",
        25, 1),
       (5,
        "Nie bez powodu jest to najpopularniejszy most wśród turystów we Wrocławiu. Położony urokliwie, w zamożnej a więc i zadbanej części miasta. Ostrów Tumski to dużo obiektów sakralnych, w tych archikatedra, oraz eleganckie restauracje. W katedrze miła niespodzianka - na taras widokowy wyjeżdża się windą 😎😎😎",
        25, 1),
       (2,
        "Jak dla mnie most jest wart odwiedzenia tylko i wyłącznie przy tzw. Okazji. Jechanie do Wrocławia albo wybieranie się specjalne na Most z klódkami jak dla mnie mija się z celem. Widząc most na żywo nie szczególnie mnie zachwycił",
        25, 1),
       (4, "Miejsce bardzo klimatyczne z czeską obsługą.", 26, 1),
       (5,
        "Będąc we Wrocławiu mieliśmy ochotę zjeść czeskie dania, zachęceni opiniami wybraliśmy to miejsce. Nie zawiedliśmy się, jedzenie jest bardzo smaczne. Zamówiliśmy gulasz z knedlikiem oraz żeberka, rewelacja. Bardzo miła obsługa. Miejsce również ma fajny klimat, urządzone w czeskim stylu. Polecamy!",
        26, 1),
       (4,
        "Miejsce nietypowe. Jedzenie smaczne. Lokal bardzo mały. Obsługa miła, ale średnio zainteresowana klientem (pomocą, sugestią itp.). Hamburger ze smażonym serem to dość ciekawy wybór z menu, ale kapusta i marchewka szatkowana - pewniak rozpadającego się burgera. Może wybiorę się tu jeszcze latem, aby zjeść coś na świeżym powietrzu. I wtedy spróbuję więcej wyciągnąć informacji i specjałach kuchni czeskiej.",
        26, 1)
;



