USE planer;

INSERT INTO city(name, description)
VALUES ("Gdańsk",
        "Miasto w województwie pomorskim, położone nad Morzem Bałtyckim u ujścia Motławy do Wisły nad Zatoką Gdańską.\nCentrum kulturalne, naukowe i gospodarcze oraz stolica województwa pomorskiego."),
       ("Gdynia",
        "Miasto w województwie pomorskim, położone nad Morzem Bałtyckim. Wchodzi w skład Trójmiasta (wraz z Gdańskiem i Sopotem).\nJest najludniejszym w Polsce miastem niewojewódzkim z wieloma ciekawymi restauracjami i dostępem do plaży."),
       ("Warszawa",
        "Stolica Polski i województwa mazowieckiego, największe miasto w kraju, położone w jego centralnej części,\nna Nizinie Środkowomazowieckiej, na Mazowszu, nad Wisłą."),
       ("Kraków",
        "Miasto położone w południowej Polsce nad Wisłą, drugie co do liczby mieszkańców i powierzchni miasto kraju.\nFormalna stolica Polski do 1795 roku i miasto koronacyjne oraz nekropolia królów Polski. Kraków jest stolicą historycznej Małopolski.\nLeży na obszarze Bramy Krakowskiej, Niecki Nidziańskiej i Pogórza Zachodniobeskidzkiego."),
       ("Wrocław",
        "Miasto w południowo-zachodniej Polsce. Położone na Nizinie Śląskiej, nad Odrą i czterema jej dopływami.\nJest historyczną stolicą Dolnego Śląska, a także całego Śląska. Jest głównym miastem aglomeracji wrocławskiej.\nTrzecie pod względem liczby ludności miasto w Polsce");


INSERT INTO place (description, name, number_of_opinions, price, rate, type, city_id)
VALUES ("Bazylika konkatedralna Wniebowzięcia Najświętszej Maryi Panny, zwana często „Koroną Gdańska” jest największą w Europie świątynią wybudowaną z cegły.Jej potężne mury i wieże wznoszą się wysoko nad panoramą miasta oraz nad rozległą okolicą.",
        "Bazylika Mariacka",
        20,
        12,
        4,
        "MONUMENT",
        1),
       ("Wzgórze Pachołek z 15 metrową wieżą widokową znajdujące się w Oliwie. Można podziwiać wspaniałą panoramę Gdańska oraz pospacerować lasem.",
        "Wzgórze Pachołek-Wieża Widokowa",
        11,
        0,
        5,
        "NATURE",
        1),
       ("Zabytkowy park w dzielnicy Oliwa, nad Potokiem Oliwskim. Powierzchnia parku wynosi 11,3 ha.",
        "Park Oliwski",
        5,
        0,
        4.5,
        "NATURE",
        1),
       ("Zabytkowa fontanna. Stoi w najbardziej reprezentacyjnej części Gdańska – na Długim Targu, przed wejściem do Dworu Artusa.",
        "Fontanna Neptuna",
        10,
        0,
        4,
        "MONUMENT",
        1),
       ("Mieszanka rutyny, młodości, pasji, perfekcjonizmu, elementy polskiej tradycji, powiew kuchni świata, super pierogi. Kilka lokalizacji w Gdańsku",
        "Pierogarnia Mandu",
        21,
        0,
        4.7,
        "RESTAURANT",
        1),
       ("Dwa wieżowce o charakterze mieszkalnym i biurowo-usługowym zlokalizowane w śródmieściu Gdyni, zbudowane w latach 2006-2009. Całkowita wysokość wyższej wieży to 141,6 m, a niższej 91 m.W rankingu wysokości wieżowców Polsce wyższa wieża znajduje się na 12. miejscu. Można wjechać na punkt widokowy.",
        "Sea Towers",
        10,
        20,
        4,
        "MONUMENT",
        2),
       ("Drewniane molo znajdujące się w nadmorskiej, południowo-wschodniej dzielnicy Gdyni. Należy do najchętniej odwiedzanych obiektów w mieście.",
        "Molo Orłowo",
        19,
        0,
        5,
        "NATURE",
        2),
       ("Długi, szybko ulegający erozji klif poprzecinany leśnymi ścieżkami. Rozciąga się z niego widok na Zatokę Gdańską.",
        "Klif Orłowski",
        15,
        0,
        4.6,
        "NATURE",
        2),
       ("Trzymasztowy żaglowiec szkolny zakupiony przez społeczeństwo Pomorza w 1929 dla Szkoły Morskiej w Gdyni. Od 1982 zacumowany w Gdyni jako statek-muzeum, oddział Narodowego Muzeum Morskiego w Gdańsku.",
        "Statek-Muzeum Dar Pomorza",
        5,
        26,
        4.2,
        "MONUMENT",
        2),
       ("NEON to kuchnia z azjatyckim twistem. Wszystkie potrawy są przygotowywane na miejscu. W kuchni rządzi Jan Kilański - laureat polskiego Top Chefa.",
        "Neon",
        13,
        0,
        4.6,
        "RESTAURANT",
        2),
       ("Pałac Kultury i Nauki drugi pod względem wysokości całkowitej budynek w Polsce. Znajduje się w śródmieściu Warszawy, przy placu Defilad 1.W 2007 budynek został wpisany do rejestru zabytków. Pałac stanowił dar narodu radzieckiego dla narodu polskiego. Możliwośc wjechania na taras widokowy oraz zwiedzenia muzeum.",
        "Pałac Kultury i Nauki",
        25,
        20,
        4.6,
        "MONUMENT",
        3),
       ("Barokowo-klasycystyczny zamek królewski znajdujący się w Warszawie przy placu Zamkowym 4. Pełni funkcje muzealne i reprezentacyjne. Pierwotnie rezydencja książąt mazowieckich, a od XVI wieku siedziba władz I Rzeczypospolitej: króla i Sejmu.",
        "Zamek Królewski w Warszawie",
        21,
        15,
        3.9,
        "MONUMENT",
        3),
       ("Park miejski w śródmieściu Warszawy, położony między placem marsz. Józefa Piłsudskiego, placem Żelaznej Bramy, ul. Marszałkowską i ul. Królewską, na Osi Saskiej.Pierwotnie geometryczny ogród francuski założony w latach 1724-1748 dla króla Augusta II Mocnego jako ogród pałacu Saskiego.",
        "Ogród Saski w Warszawie",
        13,
        0,
        4.3,
        "NATURE",
        3),
       ("Zespół pałacowo-ogrodowy w Warszawie założony w XVIII wieku przez Stanisława Augusta Poniatowskiego. Nazwa pochodzi od barokowego pawilonu Łaźni, wzniesionego w latach 80.XVII wieku przez Stanisława Herakliusza Lubomirskiego i przebudowanego przez Stanisława Augusta Poniatowskiego na pałac Na Wyspie.",
        "Łazienki Królewskie",
        30,
        0,
        4.2,
        "NATURE",
        3),
       ("Monument znajdujący się przy ul. Wybrzeże Kościuszkowskie. Rzeźba przedstawia postać Syreny z uniesionym mieczem i tarczą. Wzrok ma skierowany na północ, a jej mocny kobiecy korpus osłania trzymana w lewej ręce okrągła, lekko wypukła tarcza. Na tarczy znajduje się wizerunek orła w koronie, wokół którego biegnie napis Warszawa",
        "Pomnik Syreny nad Wisłą",
        10,
        0,
        4.7,
        "MONUMENT",
        3),
       ("Bezpretensjonalna restauracja serwująca koktajle oraz pizzę w stylu neapolitańskim z różnymi dodatkami.",
        "Pizzaiolo",
        28,
        0,
        4.4,
        "RESTAURANT",
        3),
       ("Zamek obronno-rezydencyjny w Krakowie, na wzgórzu Wawelskim.Mają w nim siedzibę Państwowe Zbiory Sztuki - Zamek Królewski na Wawelu, muzeum o powierzchni 7040 m² z 71 salami wystawowymi.",
        "Zamek Królewski na Wawelu",
        21,
        40,
        4.3,
        "MONUMENT",
        4),
       ("Sukiennice - zabytkowy budynek sukiennic znajdujący się w Krakowie na Starym Mieście, pośrodku Rynku Głównego. ",
        "Sukiennice",
        31,
        0,
        5.0,
        "MONUMENT",
        4),
       ("Planty - park miejski w Krakowie otaczający Stare Miasto. Został założony w latach 1822-1830, ma powierzchnię 21 ha i ok. 4 km długości.",
        "Planty",
        13,
        0,
        4.9,
        "NATURE",
        4),
       ("Kopiec Kościuszki - jeden z pięciu kopców krakowskich, poświęcony Tadeuszowi Kościuszce, znajduje się na Górze św. Bronisławy w zachodniej części Krakowa na terenie Dzielnicy VII Zwierzyniec.",
        "Kopiec Kościuszki",
        21,
        0,
        4.2,
        "NATURE",
        4),
       ("Kameralna, przytulna restauracja z 2 salami i barem serwująca pożywne nowoczesne dania i szeroki wybór wódek.",
        "Restauracja Starka Kraków",
        11,
        0,
        4.0,
        "RESTAURANT",
        4),
       ("Muzeum sztuki we Wrocławiu, założone w 1893 we Lwowie, od 1980 we Wrocławiu eksponuje cykloramiczny obraz Bitwa pod Racławicami namalowany w latach 1893-1894 przez zespół malarzy pod kierunkiem Jana Styki i Wojciecha Kossaka. ",
        "Muzeum Panorama Racławicka",
        19,
        25,
        4.8,
        "MONUMENT",
        5),
       ("Znajduje się w Parku Szczytnickim w Śródmieściu Wrocławia. W ogrodzie zgromadzono prawie 270 taksonów 		roślin drzewiastych. ",
        "Ogród Japonski",
        25,
        0,
        4.7,
        "NATURE",
        5),
       ("Średniowieczny plac targowy we Wrocławiu, obecnie centralna część strefy pieszej. Jeden z największych rynków staromiejskich Europy, z największymi ratuszami w Polsce. Rynek wrocławski, według Olgierda Czernera, obejmuje cały teren placu wraz z wszystkimi elementami architektonicznymi znajdującym się na jego obszarze oraz zabudowę otaczającą plac z czterech stron.",
        "Wrocławski Rynek",
        31,
        0,
        4.5,
        "NATURE",
        5),
       ("Dwuprzęsłowy stalowy, nitowany most we Wrocławiu zbudowany w roku 1889 nad północną odnogą Odry pomiędzy Ostrowem Tumskim a Wyspą Piasek, na miejscu wcześniejszego mostu drewnianego",
        "Most Tumski",
        10,
        0,
        3.9,
        "NATURE",
        5),
       ("Tradycyjne czeskie potrawy, kawa i piwo w rustykalnym lokalu z tarasem.",
        "Pepik PUB",
        29,
        0,
        4.7,
        "RESTAURANT",
        5);



INSERT INTO image (url, place_id)
VALUES ("https://s-trojmiasto.pl/zdj/c/n/9/2825/999x0/2825085-Bazylika-Mariacka-to-najwiekszy-w-Europie-kosciol-wzniesiony-z-cegly-Jej-budowa-trwala-ok-150-lat-a-dokladnie-odbyla-sie-w-latach-1346-1502.jpg",
        1),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/48343.jpg", 2),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/23139.jpg", 2),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/48853.jpg", 2),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/48879.jpg", 2),
       ("https://download.cloudgdansk.pl/gdansk-pl/t/202208193602.jpg", 2),
       ("https://odkryjpomorze.pl/obrazy_obiektow/2442/23137.jpg", 2),
       ("https://v.wpimg.pl/NTI4MzA5YTUoVjtJbk5sIGsObxMoF2J2PBZ3WG56YWJ9BDVOcwJhPWdDPVQxWWE1ZlJiEDFQKXt6BXtKcho-NTtfEhUtXDknIl0SKiBBPC0iawYVMlgnMCxGYxAxUCl2NA",
        3),
       ("https://wenecjusz.pl/wp-content/uploads/2019/12/gdansk-20-1.jpg", 4),
       ("https://pojedztam.pl/wp-content/uploads/2019/04/Pierogarnia-Mandu-w-Gdansku.jpg", 5),
       ("https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/00_sea_towers_%28April_2018%29.jpg/1280px-00_sea_towers_%28April_2018%29.jpg",
        6),
       ("https://yacht-club-sea-towers-premium-gdynia.booked.com.pl/data/Photos/OriginalPhoto/11918/1191817/1191817516/Yacht-Club-Sea-Towers-Premium-Apartment-Gdynia-Exterior.JPEG",
        6),
       ("https://i.wpimg.pl/960x720/i1.nocimg.pl/d13/1721/153-gdynia-sylwester-2014-2015.png", 6),
       ("https://www.baltica-apartments.pl/wp-content/uploads/2017/08/45894fotolia-132187134-subscription-monthly-xxlw1170h610-720x371.jpg",
        6),
       ("https://www.worldisbeautiful.eu/up_files/1175-Molo-w-Orlowie.jpg", 7),
       ("https://www.gdynia.pl/cache/images/1400x0/b64b1f75ee97d390c14d0eae3a1b5b41.jpg", 8),
       ("https://nmm.pl/wp-content/uploads/2021/10/01_Dar-Pomorza.jpg", 9),
       ("https://lh3.googleusercontent.com/p/AF1QipMNNW7wQfAf93F3rFxIRrOUp6RFChN0_-f2L8SU=w1080-h608-p-no-v0", 10),
       ("https://pkin.pl/wp-content/uploads/articles/phpu0wsSU_5ae85fdb14f5a.jpg", 11),
       ("https://www.zamek-krolewski.pl/sites/default/files/2022/03/1342/fotorelacja/120921%20ZAMEK%20DRON%2030.jpg",
        12),
       ("https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Warszawa-Ogr%C3%B3d_Saski_fontanna.jpg/240px-Warszawa-Ogr%C3%B3d_Saski_fontanna.jpg",
        13),
       ("https://warsawtour.pl/wp-content/uploads/2018/08/%C5%81azienki-Kr%C3%B3lewskie-Pa%C5%82ac-na-Wyspie_fot.-m.st_.-Warszawa.jpg",
        14),
       ("https://4.bp.blogspot.com/-8SzFMKoYagw/WLx23r7ZRdI/AAAAAAAAQ54/2OXTr9wT1AslI5SBPWFC907AdC4_OyozwCLcB/s1600/syrena%2B4.jpg",15),
       ("https://4.bp.blogspot.com/-ssHOb3qMUy0/WLx23TPpNyI/AAAAAAAAQ50/ZBcRAgH9x_0qS9tEzrfOCo-GIz6PejDVgCLcB/s1600/syrena%2B1.jpg",
        15),
       ("https://pyzamadeinpoland.pl/wp-content/uploads/2020/11/pizzaiolo-dwa-osiem-11.jpg", 16),
       ("https://assets.ey.com/content/dam/ey-sites/ey-com/pl_pl/home-index/ey-cracow-shutterstock_1783414247.jpg", 17),
       ("https://www.ing.pl/_fileserver/item/1125389.fedcba", 17),
       ("https://krakowbooking.com/wp-content/uploads/2021/05/rsz_istock-655737662_adobespark-1024x768.jpg", 17),
       ("https://ocdn.eu/images/pulscms/OGI7MDA_/385cba4c-1b9e-4015-88e3-dec6ae892f20.jpeg", 17),
       ("http://media.krakow.travel/photos/49539/xxl.jpg", 18),
       ("https://meteor-turystyka.pl/images/places/0/28.jpg", 18),
       ("https://www.national-geographic.pl/media/cache/big/uploads/media/default/0014/39/krakow.jpeg", 18),
       ("https://www.morizon.pl/blog/wp-content/uploads/2015/06/krakow-4439817_640.jpg", 18),
       ("https://krakow.wiki/wp-content/uploads/2016/10/planty.jpg", 19),
       ("https://cdn.getyourguide.com/img/tour/a2568e7d9fc18e02.jpeg/145.jpg", 20),
       ("https://jura.slaskie.travel/Media/Default/.MainStorage/ContentItemDocumentTypeRecord/oyd0r1it.bso/starka1.jpg",
        21),
       ("https://www.niesamowitapolska.eu/images/dolnoslaskie/wroclaw-i-okolice/artykuly/panorama-raclawicka/FD8A6441.JPG",
        22),
       ("https://s3.eu-central-1.amazonaws.com/pressland-cms/cache/article_show_cover/3a/6175486-ogrod-japonski-to-brama-wejsciowa-do-uchi-roji-dalej.jpeg",
        23),
       ("https://i.wpimg.pl/O/644x429/d.wpimg.pl/1682314221--1017701063/wroclaw-rynek-miejski.jpg", 24),
       ("https://explorista.nl/wp-content/uploads/2019/04/Wroclaw2.jpg", 24),
       ("https://www.geogr.uni.wroc.pl/ts1/r=w:2000%7Ch:1500&img=tourism_and_hospitality_blog/14/lib-01.jpg", 24),
       ("https://mapy.emiejsca.pl/zdjecia/wroclaw-klodki-most-tumski-32.jpg", 25),
       ("https://wroclawskiejedzenie.pl/wp-content/uploads/2015/05/Pepik-10-765x1024.jpg", 26);

-- # INSERT INTO user (login, name, email, password, role, locked, enabled)
-- # VALUES ("singapore",
-- #         "Trip",
-- #         "singapore@gmail.com",
-- #         password,
-- #         null,
-- #         null,
-- #         null
-- #         )
